version: "3.5"
services:
  # web:
  #   container_name: main_web
  #   restart: always
  #   networks:
  #     - Starting-up
  #   build: https://github.com/headStyleColorRed/startingUp-Web.git
  #   ports:
  #     - "80:80"
  server:
    container_name: login_server
    restart: always
    networks: 
      - Starting-up
    build: https://github.com/headStyleColorRed/startingUp-Login.git
    ports:
      - "8888:8888"
    links:
      - mongo
  mongo:
    container_name: login_DB
    networks: 
      - Starting-up
    image: mongo
    ports:
      - "27017:27017"

networks:
  Starting-up:
    name: Starting-up