version: "3.5"
services:
  app:
    container_name: login
    restart: always
    networks: 
      - E-skeleton
    build: .
    ports:
      - "8888:8888"
    links:
      - mongo
  mongo:
    container_name: mongo
    networks: 
      - E-skeleton
    image: mongo
    ports:
      - "27017:27017"

networks:
  E-skeleton:
    name: E-skeleton